### ISSUE TITLE
Use DTOs to map requests (using MapRequestPayload & MapQueryString)

### ISSUE THREAD

**Issue by BafS** [symfony/demo#1434] opened 2023-10-10 13:15 UTC
The demo is a good place to show the best practices. Now that we have the new attributes to map requests to DTOs (`MapRequestPayload` & `MapQueryString`) I think it would be great to use them in the demo. It would also help to see some potential issues we can hit using those (there are some open issues related to that).

If you think we should not, feel free to close this issue.

**Comment by 94noni** [comment] 2023-10-13 07:21
I like the idea on my side
there were already a pass on using attributes, this can also showcase some nice new usage :)

**Comment by javiereguiluz** [comment] 2023-10-13 08:15
I'm not sure about making this change.

The reason is that I don't know how popular is this technique among Symfony developers.

I fear that newcomers see it and think that Symfony is more complex/cumbersome than it really is.

Maybe we could do it only in one controller and clearly explain that "all this complication" is totally optional. It's nice for complex apps that will be maintained in the future, but it's overkill for other simpler apps.

**Comment by BafS** [comment] 2023-10-13 16:06
@javiereguiluz thanks for your feedback. Valid point for sure. In the other hand, doing it in the demo could also help devs to make the move.

If we were to do it partially (which I think is a good idea), what would you choose? Maybe the admin part could be a good contender.

**Comment by BafS** [comment] 2023-12-26 14:15
Any new about this issue? The PR is open since October

**Comment by BafS** [comment] 2024-03-09 21:21
It's been 6 months, any chance? Shall I just close it?

**Comment by javiereguiluz** [comment] 2024-03-11 09:15
@BafS sorry for not having made a decision earlier. The problem I see here is that this is a fantastic Symfony feature ... but in this Symfony Demo project it looks more cumbersome than useful. The feature doesn't shine at all ... probably because the Symfony Demo app is very simple by design.

So, let's close this for now as "won't fix" ... and we can revisit this in the future. I'm sorry your proposal didn't make it this time.

**Closed by javiereguiluz** 2024-03-11 09:15 UTC

**Comment by BafS** [comment] 2024-03-11 09:32
Could we have another demo for "API" purpose? Or a new "API" module? Symfony is often use for Rest APIs but the demo doesn't really show this because it uses the "fullstack" version of Symfony.

**Comment by javiereguiluz** [comment] 2024-03-11 10:09
@BafS I think it would be nice to have an API-only demo ... but:

* I don't think we can do that ourselves (i.e. the Symfony company) because we don't have resources to create another demo project and we're not true experts in APIs;
* Given that the API Platform project exists and it's very popular to build APIs with Symfony, maybe we can link to their demo project somewhere to guide newcomers to it.

What do you think?
