### ISSUE TITLE
deprecation message after update

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#838] opened 2018-07-20 09:31 UTC
after composer update

  - Updating doctrine/common (v2.8.1 => v2.9.0): 
  - Updating doctrine/dbal (v2.7.1 => v2.8.0):
  - Updating doctrine/orm (v2.6.1 => v2.6.2):

I receive deprecation warnings

User Deprecated: Doctrine\Common\ClassLoader is deprecated.
[
  "exception" => ErrorException {#4677 
    #message: "User Deprecated: Doctrine\Common\ClassLoader is deprecated."
    #code: 0
    #file: "/var/www/.../vendor/doctrine/common/lib/Doctrine/Common/ClassLoader.php"
    #line: 7
    #severity: E_USER_DEPRECATED

**Comment by stof** [comment] 2018-07-20 10:47
that's because the doctrine ORM still uses the deprecated class. There is already a work in progress in the ORM to remove it, but not released as 2.6.3 yet.

**Comment by javiereguiluz** [comment] 2018-07-20 13:04
Christophe, thanks for the info. We're closing here because the issue is being solved in another repository ... and this will disappear next time we update dependencies. Thanks!

**Closed by javiereguiluz** 2018-07-20 13:04 UTC
