### ISSUE TITLE
ClassNotFoundError DebugBundle

### ISSUE THREAD

**Issue by ma-si** [symfony/demo#1120] opened 2020-05-27 15:27 UTC
composer install --no-dev
APP_ENV=prod

**Comment by javiereguiluz** [comment] 2020-11-02 07:51
I'm closing this as "can't reproduce":

```
$ git clone git@github.com:symfony/demo.git
$ cd demo/
$ composer install --no-dev
$ (edit the .env file and set APP_ENV=prod)
$ symfony serve
```

Browse the app and you won't see any error. If you can share other steps to fully reproduce the error, we'll reopen this. Thanks!

**Closed by javiereguiluz** 2020-11-02 07:51 UTC
