### ISSUE TITLE
User Deprecated: Since twig/twig 3.10

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1518] opened 2024-05-15 09:23 UTC
after update

Upgrading twig/twig (v3.10.1 => v3.10.2): Extracting archive

User Deprecated: Since twig/twig 3.10: The "Twig\Extension\EscaperExtension::addSafeClass()" method is deprecated, use the "Twig\Runtime\EscaperRuntime::addSafeClass()" method instead.

**Comment by derrabus** [comment] 2024-05-15 09:38
Duplicate of symfony/ux#1844.

**Closed by derrabus** 2024-05-15 09:38 UTC

**Comment by lxregistry** [comment] 2024-05-20 13:30
this deprecation notice still persist
 Installing twig/twig (v3.10.3): Extracting archive

User Deprecated: Since twig/twig 3.10: The "Twig\Extension\EscaperExtension::addSafeClass()" method is deprecated, use the "Twig\Runtime\EscaperRuntime::addSafeClass()" method instead.

**Comment by derrabus** [comment] 2024-05-20 17:34
Please use https://github.com/symfony/symfony/discussions for support questions.
