### ISSUE TITLE
I would like create new user but i obtain this error

### ISSUE THREAD

**Issue by Anouchka25** [symfony/demo#827] opened 2018-06-26 10:34 UTC
Hi
I created UserController.php and i would like create new user but i obtain this error : 

> Return value of App\Entity\User::getFullName() must be of the type string, null returned

I don't understand this error ! My User.php is same that demo !
Thanks to help me

**Comment by SundownDEV** [comment] 2018-06-27 13:58
Can you post your UserController code ? And optionnally the setters/getters of the user entity if you edited them.

**Comment by OlivierToussaint** [comment] 2018-06-27 15:30
https://github.com/Anouchka25/MyTopBlog/blob/master/src/Controller/UserController.php

I think it's this UserController

```
public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('user_index');
        }
        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
```

You can't user $user to twig because in the entity https://github.com/symfony/demo/blob/master/src/Entity/User.php getFullName is typed in string and not ?string and this entity is null for the moment ($user = new User())

Just remove ```  'user' => $user,```

**Comment by javiereguiluz** [comment] 2018-07-18 07:10
Let's close this as "fixed" because the default code in this app seems to work as expected and this issue may come from some changes done in the app while experimenting with it. Thanks @OlivierToussaint for your help! @Anouchka25 if you can reproduce the error with the unmodified code of this app, please reopen this issue. Thanks!

**Closed by javiereguiluz** 2018-07-18 07:10 UTC
