### ISSUE TITLE
Could not find any fixture services to load.

### ISSUE THREAD

**Issue by lbm-services** [symfony/demo#728] opened 2017-12-09 21:00 UTC
After changing .env to mysql doctrine:schema:create finished successful.
doctrine:fixtures:load
Could not find any fixture services to load.

**Comment by javiereguiluz** [comment] 2017-12-10 19:50
The fixtures of this app are stored in `src/DataFixtures/`, which doesn't work when the DoctrineFixturesBundle is old. We recently update this bundle to 3.0.2 version. Are you using the same version?

Independently from the previous comment, you can execute the command as follows to make it work no matter which version of fixtures bundle you use:

```bash
$ php bin/console doctrine:fixtures:load --fixtures=src/DataFixtures/
```

**Comment by DavertMik** [comment] 2017-12-10 23:22
Thanks, but I get this
```
php bin/console doctrine:fixtures:load --fixtures=src/DataFixtures/

                                           
  The "--fixtures" option does not exist.  
                                           

doctrine:fixtures:load [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```
Current package set:

```
doctrine/cache                      v1.7.1            Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.5.0            Collections Abstraction library
doctrine/common                     v2.8.1            Common Library for Doctrine projects
doctrine/data-fixtures              v1.3.0            Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.6.3            Database Abstraction Layer
doctrine/doctrine-bundle            1.8.1             Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.2             Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   3.0.1             Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v1.3.1            Symfony DoctrineMigrationsBundle
```

**Comment by DavertMik** [comment] 2017-12-11 00:08
Same behavior with 

```
doctrine/doctrine-fixtures-bundle   3.0.2             Symfony DoctrineFixturesBundle
```
See:

```
php bin/console doctrine:fixtures:load       
Careful, database will be purged. Do you want to continue y/N ?y

In LoadDataFixturesDoctrineCommand.php line 95:
                                                
  Could not find any fixture services to load.  
                                                

doctrine:fixtures:load [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

**Comment by lbm-services** [comment] 2017-12-11 20:34
Why don t you guys simply provide an sql file for mysql users? Nobody wants to work with sqlite, I guess.

**Comment by bocharsky-bw** [comment] 2017-12-11 21:25
@lbm-services The answer is simple, this demo version should work in one click, I mean `composer create-project`, i.e. we don't want to enforce users do extra steps to bootstrap this project like making sure they have MySQL server, creating DB, creating schema, loading fixtures etc. that's why SQLite DB with dummy data fits perfect here

**Comment by lbm-services** [comment] 2017-12-11 22:11
I guessed that, I mean as an OPTION. 
Anyway, I made my own dumps from sqlite and imported them to MySQL. Then I ran into the pagerfanta issue (https://github.com/symfony/demo/issues/683).
But with some adjustments and bypassing the findLatest-Method, it worked.

**Comment by phpeek** [comment] 2017-12-11 22:23
@lbm-services It would be a good idea to create a dockerized fork of `symfony/demo` and run it with mysql, if You want to give a try ! ;)

**Comment by bocharsky-bw** [comment] 2017-12-12 08:17
@lbm-services Actually, you don't need any SQL file at all if you prefer MySQL. Just tweak DB credentials and use console commands:
```bash
bin/console d:d:c
bin/console d:s:c
bin/console d:f:l
```

That's it, you'll have the same dummy data you see in SQLite

**Comment by javiereguiluz** [comment] 2017-12-17 19:09
Let's close this because when using the latest DoctrineFixturesBundle (as recommended by this app) you no longer see this error. If you still see this problem, please tell us your DoctrineFixturesBundle version and the steps to reproduce. Thanks!

**Closed by javiereguiluz** 2017-12-17 19:09 UTC

**Comment by gunvantaspl** [comment] 2018-01-03 06:51
@DavertMik I also get same problem and solve it by assigning tag to the fixture. Please see the solution https://stackoverflow.com/questions/47613979/symfony-3-4-0-could-not-find-any-fixture-services-to-load/48049905#48049905

**Comment by stphane** [comment] 2018-04-05 08:59
I have two fixture loader services registered in a configuration file.  
Does anybody know how to target a specific fixture loader service using `doctrine:fixtures:load` command?

**Comment by bocharsky-bw** [comment] 2018-04-05 14:44
You probably have 2 entity managers, so you can use `--em` option to specify the proper entity manager for this command

**Comment by stphane** [comment] 2018-04-05 15:01
@bocharsky-bw I do know about the _--em_ option …  
My issue is: whatever the _entity Manager_ name I pass through that option, ALL registered _fixture loaders_ services are retrieved and their respective `load` method get called with the supplied entity manager.  
But I have two _entity managers_, each one is associated to a particular DBAL connection and each have its own _fixtures loader_ file class.   
I need to tell the Doctrine command to use a specific _fixture loader_ service with the given entity manager.  
Does this make more sense to you? Thank you.

**Comment by bocharsky-bw** [comment] 2018-04-05 16:10
Hm, what about to pass an entity manager into all fixture loaders and add a custom logic at the beginning of `load()` method, i.e. if loader does not support current entity manager - just do a `return`, otherwise - load fixtures?

**Comment by stphane** [comment] 2018-04-05 17:15
Lol that's exactly my workaround solution at the moment.

    if (strtolower($manager->getConnection()->getDatabase()) != 'acme') {
        return;
    }

But this do feel like a workaround and not a proper solution to me.  
It is the responsibility of the doctrine-fixtures-bundle (a upper level context) to feed the service with the appropriate manager and not the fixtureLoader itself IMO.  
Some sort of a service id or glob option on the command whould do the trick I guess.

**Comment by bocharsky-bw** [comment] 2018-04-05 18:10
Then probably better to create an issue in DoctrineFixturesBundle instead or make a PR :)

**Comment by rumours86** [comment] 2018-07-03 17:05
I've created a PR: https://github.com/doctrine/DoctrineFixturesBundle/pull/250
