### ISSUE TITLE
The style are not showing in browser

### ISSUE THREAD

**Issue by alexbotnaru** [symfony/demo#1272] opened 2021-11-23 14:39 UTC
I installed the application using the command : symfony new --demo my_project. It seems to work, but the styles and maybe the scripts are not working in browser, so the app looks like this: 
![image](https://user-images.githubusercontent.com/71169169/143044204-e7ac275e-d11c-450f-8306-81d77eaa9f98.png)
I tried to run some commands like : composer install, composer require symfony/webpack-encore-bundle, npm install, npm run build but the problem persists.
Any help?

**Comment by stof** [comment] 2021-11-23 14:51
Are there any errors reported in your browser console ?

**Comment by bocharsky-bw** [comment] 2021-11-23 19:03
Hm, I can't reproduce this... my steps were:

1. symfony new --demo my_project/
2. cd my_project/
3. symfony serve
4. Open https://127.0.0.1:8000/

Styles are OK to me after this. Do you use the latest version of Symfony CLI? You can check by executing `symfony self:update`. If yes, what browser and OS do you use? What browser version? It may help I think

**Comment by alexbotnaru** [comment] 2021-11-23 20:17
yeah, so I opened the project in Microsoft Edge and everythink works properly. I dont know why in Google Chrome i get those errors, as I have the last version of it (96.0.4664.45 ). Anyway, thanks a lot!

**Comment by seb-jean** [comment] 2022-03-15 10:51
@alexbotnaru, Is it resolved?

**Comment by valentin705** [comment] 2023-03-24 16:07
Hello, I just installed the Symfony demo and I have the same problem no matter what I open it with: Google Chrome, Microsoft Edge, or even Mozilla. I have the same error message as you. Do you have a solution? Thank you.

**Comment by acsig** [comment] 2023-03-28 14:37
This is still an issue. I just installed it now for the third time in a clean environment on a virtual machine. 

- downloaded the newest version today
- Win 10 prof
- xampp (8.2.0)
- composer installed (2.5.5)
- demo installed with "`composer create-project symfony/symfony-demo`"
- git installed by composer during the process
- result in edge AND chrome: css missing
- "`symfony serve`" doesn't work either
- used xampps apache server

It's hard to tell my students, that they need to install a node.js Webserver(!!!) and paket Manager npm/yarn to fix this issue. :-/ Any idea how to solve it?

**Comment by javiereguiluz** [comment] 2023-03-28 14:41
Try to run only these commands:

```
composer create-project symfony/symfony-demo
cd symfony-demo
symfony serve
```

Then browse any page, and tell us the error logs that you see in the terminal that is running `symfony serve`. Thanks.

**Comment by acsig** [comment] 2023-03-29 09:17
Looks like I found the problem: 

- I hadn't installed the `symfony-cli` binaries, thought `symfoy/console` is the same => MY FAULT! Sorry. 
- after running the demo with `symfony serve` it looked fine
- running it in the apache-environment from XAMPP NOT in the `root-directory` causes problems 
- some assets are linked to `http://localhost/build/*`, some others are linked to the subfolfers the demo is running in (which is a typical way of installing it in a teaching-environment: `http://localhost/ism/smyfony-demo/public/*`
- I still don't know where to change that
- the blogpost about the demo2 (`https://symfony.com/blog/symfony-demo-2-0-introduces-support-for-symfony-6-0`) does only implicitly mention, you have to install symfony-cli (via "best practises) and it also does not mention you have to run it in a root directory. Maybe this should be pointed out more clearly. 


![different_path](https://user-images.githubusercontent.com/53085792/228484049-6f6d1102-b923-497a-b9b6-7e1c575f6eb3.jpg)

Maybe consider the following: The symfony demo is intended to **learn and teach symfony**, to introduce people to symfony. After they installed XAMPP and composer, they're told "composer composes (a) symfony for you" BUT THEN i have to ask them to: 
- install another webserver (node.js) we actually don't use,  because we only need: 
- the included NPM package manager to 
- install ANOTHER package Manager called YARN
- this runs for several minutes and maps ca. 30k dependencies... WHY?
- Finally please install a 4th "installer" scoop to install symfony-cli which can't be installed by composer
- because scoop doesn't do the whole job, edit the path variable of your system manually. 

=> after that nobody is convinced anymore, that symfony and composer is a great, finetuned combination. :-/ 

Hope I could open your eyes a bit for problems some people might run into.

**Comment by stof** [comment] 2023-03-29 09:31
Running a website in a subdirectory requires configuring webpack-encore to make it aware of that subdirectory. The committed files in this repo use a configuration expecting a deployment at the root.

> * install another webserver (node.js)

node.js is not a webserver. It is a language runtime.

And if you just want to run the demo and not rebuild its assets, you don't need to install node, yarn and the JS dependencies. That's precisely the reason why the output of the asset building is committed in the repo instead of being ignored (as is done in most projects).
You need node.js if you want to run the asset building pipeline, because this pipeline relies on frontend tooling that is implemented in JS rather than in PHP.

**Comment by javiereguiluz** [comment] 2023-04-14 14:18
Let's close this one as hopefully fixed according to the latest comments. Thanks.

**Closed by javiereguiluz** 2023-04-14 14:18 UTC
