### ISSUE TITLE
Validation error in edit form

### ISSUE THREAD

**Issue by nicolaspetitjean** [symfony/demo#741] opened 2017-12-29 20:43 UTC
Hi

If i disable html validation in edit form and submit the form with empty value :
Type error: Argument 1 passed to App\Entity\Post::setTitle() must be of the type string, null given
<img width="1099" alt="capture d ecran 2017-12-29 a 21 42 27" src="https://user-images.githubusercontent.com/11570379/34447110-399dbcfa-ece1-11e7-8641-5b1a4539efa7.png">

**Comment by bocharsky-bw** [comment] 2017-12-30 09:36
Hm, nice catch! Sounds like a big in Symfony Validator. You can fix it with:
```php
public function setTitle(?string $title): void
```

i.e. also allow passing `null` to `setTitle()`, but I think it's just a workaround

**Comment by nicolaspetitjean** [comment] 2017-12-30 16:08
The most surprising thing is that the issue does not exists in the add form...

**Comment by javiereguiluz** [comment] 2017-12-30 16:47
I don't understand the issue well. You are visiting the password-protected backend, then disable the HTML validation using the browser code inspector and submit the form. The application responds with an error page and the wrong post is not added in the database. Is that correct or am I missing something? Thanks!

**Comment by nicolaspetitjean** [comment] 2017-12-30 17:34
According to entity def :
`/**
* @var string
*
* @ORM\Column(type="string")
* @Assert\NotBlank
*/
private $title;`
Empty value is not allowed, the edit form should act like the add form :
![capture du 2017-12-30 18-33-03](https://user-images.githubusercontent.com/11570379/34456141-ed706c42-ed8f-11e7-936d-b3c02b2b8335.png)
It's not the case, maybe it is me who is wrong

**Comment by bocharsky-bw** [comment] 2018-01-01 16:03
@javiereguiluz the problem only with edit form, since fields already have data. So if you clear the field, I.e. make it empty - the null value is set to the field, which fails due to strict type hint. It’s happened before validation.

With add form you won’t be able to reproduce it, because fields are set to null by default

**Comment by phpeek** [comment] 2018-01-01 21:13
Unfortunately validation doesn't work "well" with strict typing. :(

By strict typing Your entities, You're automatically preventing them from being in an invalid state.

I was not able to find reasonable workaround for those types of situations, this is why I'm looking into what are You going to suggest here. :)

What I'm doing in those kind of situations is either what @bocharsky-bw suggested - marking setter arguments as nullable `?string` or setting `'empty_data' => ''` when building form fields. Both of those approaches are not really elegant, though I find the first approach to cause less head scratching. :)

**Comment by bocharsky-bw** [comment] 2018-01-01 22:24
I'm probably leaning toward leaving it as is, I don't like the idea of adding `?string` which would make affected entities a bit "dirty".

Actually, if you already created an entity - you already filled out those required fields, which means that it's a really rare and odd case when you totally clear those fields. The only thing you would probably want to do in practice - just tweak them

**Comment by javiereguiluz** [comment] 2018-01-02 08:49
I still don't understand anything here 😅 

@bocharsky-bw you tell me that this happen in the edit form, but if I:

1) Edit any blog post
2) Remove the title and summary fields
3) Submit the form

I see a browser validation error saying that those fields cannot be left empty. So, I'd say there's no error here.

-----

If I disable the validation with my browser inspector, I can submit the wrong form with the empty fields ... but the validation is done in the backend and I see an error page. No data is change in the database and the empty blog post fields are simply ignored and everything is back to normal. So, I'd say there's no error here either.

**Comment by nicolaspetitjean** [comment] 2018-01-02 09:01
@javiereguiluz I disabled html validation directly in edit form def:
`{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}`
Then i submit the empty form (you need to remove values before..). I don't use my browser inspector and i don't remove dom elements either.
I never use html validation when developing, and you can't trust them.

**Comment by javiereguiluz** [comment] 2018-01-02 09:11
Note: HTML validation is not for trusting, it's for convenience for normal people (not hackers, etc.)

I see the problem now. In practice it doesn't matter because you'll see an error message and the entity won't end up with wrong data ever. But I guess you want to display a better error message.

My vote would go to replace `string` by `?string` where needed.

**Comment by nicolaspetitjean** [comment] 2018-01-02 15:46
Sounds like it is the best solution right now

**Comment by javiereguiluz** [comment] 2018-01-31 12:27
Closing as probably fixed by #757. Thanks!

**Closed by javiereguiluz** 2018-01-31 12:27 UTC
Labels: bug

**Comment by ahmed-bhs** [comment] 2018-11-30 19:16
Can someone explain  why with new form, the validation script is hitted before the entity binding data via setters, and with form edit, the entity binding is hitted before validation ?
