### ISSUE TITLE
translations not working

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#704] opened 2017-11-23 18:24 UTC
hello,
installed today latest version with git clone

An exception has been thrown during the rendering of a template ("Invalid resource provided: "1.2"; Errors: [WARNING 1549] failed to load external entity "file:////var/www/vhosts/test.domain/symfony/vendor/symfony/translation/Loader/schema/dic/xliff-core/xml.xsd" (in n/a - line 0, column 0)

**Comment by javiereguiluz** [comment] 2017-11-28 15:08
I can't reproduce this error. During the last days we changed translations from translations/ to config/translations/ and then back to translations/. The definitive dir is `translations/`. Can you check if the files are in that directory?

**Comment by bogdandovgopol** [comment] 2017-11-29 03:59
Working for me just fine.

**Comment by bogdandovgopol** [comment] 2017-11-29 03:59
@javiereguiluz Working for me just fine.

**Comment by piotrgradzinski** [comment] 2017-12-01 11:39
@javiereguiluz - works OK for me too. Can't reproduce.

**Comment by javiereguiluz** [comment] 2017-12-01 14:48
OK, thanks for your comments. I'm closing this issue then until we have more information about how to reproduce it. Thanks!

**Closed by javiereguiluz** 2017-12-01 14:48 UTC
Labels: bug, NEEDS COMMENTS
